// Generated by scripts/yume_cli.py from docs/src/en_US/cli/yume-gui.cli. Do not edit.
//
// YUME - Yume Universal Multiprotocol Engine
// Copyright (C) 2020-2026  FixCraft Inc.
// Licensed under the GNU Affero General Public License v3.0 or later.
//
// The option model lives in the yume_gui_1 manual source. Edit the
// @opt and @cli entries there, then run scripts/yume_cli.py sync.

#pragma once

namespace yume::gui::help {

inline constexpr char kHelpBody[] =
    "Usage:\n"
    "  yume-gui [--kit <name>] [window options]\n"
    "  yume-gui [--kit <name>] [window options] --capture <directory>\n"
    "  yume-gui --kit <name> [--yume <path>] --headless <action>\n"
    "  yume-gui [--yume <path>] --import-kit <file> --name <name>\n"
    "  yume-gui --version\n"
    "  yume-gui --help\n"
    "\n"
    "Options:\n"
    "  --kit <name>             Show this kit first\n"
    "  --yume <path>            Run this yume program instead of the one beside yume-gui\n"
    "  --version                Print the version and the Qt in use\n"
    "  -h, --help               Print this help and exit\n"
    "\n"
    "Window options:\n"
    "  --page <page>            Open this page: overview, connect, logs or posture\n"
    "  --theme <theme>          Use light, dark or the system's theme for this run\n"
    "  --layout-direction <direction>\n"
    "                           Lay the window out left to right or right to left\n"
    "  --size <size>            Open the window at this size, such as 1280x800\n"
    "  --no-tray                Show no tray icon, so closing the window quits the GUI\n"
    "\n"
    "Tests and automation:\n"
    "  --capture <directory>    Save every page as an image, then exit\n"
    "  --headless <action>      Act on --kit without a window: status, connect, stop or cycle\n"
    "  --import-kit <file>      Import a sealed kit with the code on standard input, with --name\n"
    "  --name <name>            The name of the kit --import-kit creates\n"
    "\n"
    "The GUI talks to each yume only through its control socket.\n"
    "A tunnel keeps running when the window closes.\n";

inline constexpr char kBashCompletion[] =
    "# bash completion for yume-gui\n"
    "_yume-gui_complete() {\n"
    "  local cur prev\n"
    "  cur=\"${COMP_WORDS[COMP_CWORD]}\"\n"
    "  prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n"
    "  local opts=\"-h --capture --headless --help --import-kit --kit --layout-direction --name --no-tray --page --size --theme --version --yume\"\n"
    "  local file_opts=\"--capture --import-kit --yume\"\n"
    "  case \"$prev\" in\n"
    "    --page)\n"
    "      COMPREPLY=( $(compgen -W \"overview connect logs posture\" -- \"$cur\") )\n"
    "      return 0\n"
    "      ;;\n"
    "    --theme)\n"
    "      COMPREPLY=( $(compgen -W \"light dark system\" -- \"$cur\") )\n"
    "      return 0\n"
    "      ;;\n"
    "    --layout-direction)\n"
    "      COMPREPLY=( $(compgen -W \"ltr rtl\" -- \"$cur\") )\n"
    "      return 0\n"
    "      ;;\n"
    "    --headless)\n"
    "      COMPREPLY=( $(compgen -W \"status connect stop cycle\" -- \"$cur\") )\n"
    "      return 0\n"
    "      ;;\n"
    "  esac\n"
    "  for opt in $file_opts; do\n"
    "    if [[ \"$prev\" == \"$opt\" ]]; then\n"
    "      COMPREPLY=( $(compgen -f -- \"$cur\") )\n"
    "      return 0\n"
    "    fi\n"
    "  done\n"
    "  if [[ \"$cur\" == -* ]]; then\n"
    "    COMPREPLY=( $(compgen -W \"$opts\" -- \"$cur\") )\n"
    "    return 0\n"
    "  fi\n"
    "  COMPREPLY=()\n"
    "}\n"
    "complete -F _yume-gui_complete yume-gui\n";

}  // namespace yume::gui::help
