// Generated by scripts/yume_cli.py from docs/src/en_US/cli/yumed.cli. Do not edit.
//
// YUME - Yume Universal Multiprotocol Engine
// Copyright (C) 2020-2026  FixCraft Inc.
// Licensed under the GNU Affero General Public License v3.0 or later.
//
// The option model lives in the yumed_8 manual source. Edit the
// @opt and @cli entries there, then run scripts/yume_cli.py sync.

#pragma once

namespace yume::runtime::yumed_cli {

inline constexpr char kHelpBody[] =
    "Usage:\n"
    "  yumed --config <path> [--validate]\n"
    "  yumed --version\n"
    "  yumed --help\n"
    "\n"
    "Options:\n"
    "  --config <path>          Read a schema-1 configuration\n"
    "  --validate               Check local configuration and credentials, then exit\n"
    "  --version                Print local versions and provider information\n"
    "  -h, --help               Print this help and exit\n"
    "\n"
    "Network and security policy come only from the schema-1 configuration.\n"
    "This development runtime is not qualified for production use.\n";

}  // namespace yume::runtime::yumed_cli
