// Generated by scripts/yume_cli.py from docs/src/en_US/cli/yume.cli. Do not edit.
//
// YUME - Yume Universal Multiprotocol Engine
// Copyright (C) 2020-2026  FixCraft Inc.
// Licensed under the GNU Affero General Public License v3.0 or later.
//
// The option model lives in the yume_1 manual source. Edit the
// @opt and @cli entries there, then run scripts/yume_cli.py sync.

#pragma once

namespace yume::runtime::yume_cli {

inline constexpr char kHelpBody[] =
    "Usage:\n"
    "  yume --config <path> [--validate] [run settings] [evidence]\n"
    "  yume --config <path> --status\n"
    "  yume --version\n"
    "  yume --completion bash\n"
    "  yume --help\n"
    "\n"
    "Options:\n"
    "  --config <path>          Read a schema-1 configuration\n"
    "  --validate               Check local configuration and credentials, then exit\n"
    "  --status                 Print the running client's state from its control socket\n"
    "  --version                Print local versions and provider information\n"
    "  --completion <shell>     Print the shell completion script and exit\n"
    "  -h, --help               Print this help and exit\n"
    "\n"
    "Run settings:\n"
    "  --connect <ip>           Dial this IP address instead of the host\n"
    "  --socks-address <ip>     Listen for SOCKS5 on 127.0.0.1 or ::1\n"
    "  --socks-port <port>      Listen for SOCKS5 on this port\n"
    "\n"
    "Evidence:\n"
    "  --outer-carrier-evidence <path>\n"
    "                           Write a report on the first connection's outer carrier\n"
    "\n"
    "Security policy comes only from the schema-1 configuration.\n"
    "This development runtime is not qualified for production use.\n";

inline constexpr char kBashCompletion[] =
    "# bash completion for yume\n"
    "_yume_complete() {\n"
    "  local cur prev\n"
    "  cur=\"${COMP_WORDS[COMP_CWORD]}\"\n"
    "  prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n"
    "  local opts=\"-h --completion --config --connect --help --outer-carrier-evidence --socks-address --socks-port --status --validate --version\"\n"
    "  local file_opts=\"--config --outer-carrier-evidence\"\n"
    "  case \"$prev\" in\n"
    "    --completion)\n"
    "      COMPREPLY=( $(compgen -W \"bash\" -- \"$cur\") )\n"
    "      return 0\n"
    "      ;;\n"
    "  esac\n"
    "  for opt in $file_opts; do\n"
    "    if [[ \"$prev\" == \"$opt\" ]]; then\n"
    "      COMPREPLY=( $(compgen -f -- \"$cur\") )\n"
    "      return 0\n"
    "    fi\n"
    "  done\n"
    "  if [[ \"$cur\" == -* ]]; then\n"
    "    COMPREPLY=( $(compgen -W \"$opts\" -- \"$cur\") )\n"
    "    return 0\n"
    "  fi\n"
    "  COMPREPLY=()\n"
    "}\n"
    "complete -F _yume_complete yume\n";

}  // namespace yume::runtime::yume_cli
