// Code generated by scripts/generate_transport_profiles.py. DO NOT EDIT.

package main

var clientHelloProfiles = []clientHelloProfile{
	{
		profileID:   "chrome151-node24-v1",
		buildID:     "yume-chrome151-utls-v1.8.2-ipc-v1",
		displayName: "Chrome 151",
		buildSpec:   chrome151Spec,
	},
}

const activeHelperBuildID = "yume-chrome151-utls-v1.8.2-ipc-v1"
