// Generated by scripts/yume_cli.py from docs/src/en_US/cli/yume-doctor.cli. Do not edit.
//
// YUME - Yume Universal Multiprotocol Engine
// Copyright (C) 2020-2026  FixCraft Inc.
// Licensed under the GNU Affero General Public License v3.0 or later.
//
// The option model lives in the yume_doctor_1 manual source. Edit the
// @opt and @cli entries there, then run scripts/yume_cli.py sync.

#pragma once

namespace yume::setup::doctor_cli {

inline constexpr char kHelpBody[] =
    "Usage:\n"
    "  yume-doctor --config <path>\n"
    "  yume-doctor --help\n"
    "\n"
    "Options:\n"
    "  --config <path>          The schema-1 configuration to check\n"
    "  -h, --help               Print this help and exit\n"
    "\n"
    "The doctor reads files and starts no session.\n";

inline constexpr char kBashCompletion[] =
    "# bash completion for yume-doctor\n"
    "_yume-doctor_complete() {\n"
    "  local cur prev\n"
    "  cur=\"${COMP_WORDS[COMP_CWORD]}\"\n"
    "  prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n"
    "  local opts=\"-h --config --help\"\n"
    "  local file_opts=\"--config\"\n"
    "  case \"$prev\" in\n"
    "  esac\n"
    "  for opt in $file_opts; do\n"
    "    if [[ \"$prev\" == \"$opt\" ]]; then\n"
    "      COMPREPLY=( $(compgen -f -- \"$cur\") )\n"
    "      return 0\n"
    "    fi\n"
    "  done\n"
    "  if [[ \"$cur\" == -* ]]; then\n"
    "    COMPREPLY=( $(compgen -W \"$opts\" -- \"$cur\") )\n"
    "    return 0\n"
    "  fi\n"
    "  COMPREPLY=()\n"
    "}\n"
    "complete -F _yume-doctor_complete yume-doctor\n";

}  // namespace yume::setup::doctor_cli
