// Generated by scripts/yume_cli.py from docs/src/en_US/cli/yume-setup.cli. Do not edit.
//
// YUME - Yume Universal Multiprotocol Engine
// Copyright (C) 2020-2026  FixCraft Inc.
// Licensed under the GNU Affero General Public License v3.0 or later.
//
// The option model lives in the yume_setup_1 manual source. Edit the
// @opt and @cli entries there, then run scripts/yume_cli.py sync.

#pragma once

namespace yume::setup::setup_cli {

inline constexpr char kHelpBody[] =
    "Usage:\n"
    "  yume-setup init --host <host> --output <directory> [kit options]\n"
    "  yume-setup add-client --server <directory> --host <host>\n"
    "             --output <directory> --client-name <name> [kit options]\n"
    "  yume-setup remove-client --server <directory> --client-name <name>\n"
    "  yume-setup cluster-init --output <directory>\n"
    "  yume-setup cluster-add --cluster <directory> --server <directory>\n"
    "             --name <name> --host <host> [--address <address>] [--exit]\n"
    "  yume-setup cluster-remove --cluster <directory> --name <name>\n"
    "  yume-setup cluster-sign --cluster <directory> [--days <days>]\n"
    "  yume-setup --help\n"
    "\n"
    "Kit options:\n"
    "  --host <host>            The server's public DNS name or IP address\n"
    "  --output <directory>     New directory to create; its parent must exist\n"
    "  --server <directory>     A server directory holding yumed.json\n"
    "  --client-name <name>     The client's name in the store, client1 by default\n"
    "  --port <port>            The server's port, 443 by default\n"
    "  --max-sessions <count>   Sessions the client may hold at once, 1 to 1024\n"
    "  --weight <weight>        The client's share of the egress rate, 0.1 to 100\n"
    "  --max-egress-mbps <rate> The rate clients share by weight, in Mbit/s\n"
    "  --preset <preset>        Tuning for both sides: stealth (default), balanced,\n"
    "                             fast or max\n"
    "  --circuits               Send the client's connections through circuits\n"
    "\n"
    "Cluster options:\n"
    "  --cluster <directory>    The operator directory from cluster-init\n"
    "  --name <name>            The node's name in the cluster list\n"
    "  --address <address>      An IP address other nodes dial instead of the host\n"
    "  --exit                   Carry circuits' streams through the node's direct_tcp\n"
    "  --days <days>            Days the list stays valid, 1 to 366 (default 30)\n"
    "\n"
    "Options:\n"
    "  -h, --help               Print this help and exit\n"
    "\n"
    "init and add-client write a new directory and never replace one.\n"
    "A running yumed applies a store or list change when it reloads.\n";

inline constexpr char kBashCompletion[] =
    "# bash completion for yume-setup\n"
    "_yume-setup_complete() {\n"
    "  local cur prev\n"
    "  cur=\"${COMP_WORDS[COMP_CWORD]}\"\n"
    "  prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n"
    "  local opts=\"-h --address --circuits --client-name --cluster --days --exit --help --host --max-egress-mbps --max-sessions --name --output --port --preset --server --weight\"\n"
    "  local file_opts=\"--cluster --output --server\"\n"
    "  case \"$prev\" in\n"
    "    --preset)\n"
    "      COMPREPLY=( $(compgen -W \"stealth balanced fast max\" -- \"$cur\") )\n"
    "      return 0\n"
    "      ;;\n"
    "  esac\n"
    "  for opt in $file_opts; do\n"
    "    if [[ \"$prev\" == \"$opt\" ]]; then\n"
    "      COMPREPLY=( $(compgen -f -- \"$cur\") )\n"
    "      return 0\n"
    "    fi\n"
    "  done\n"
    "  if [[ \"$cur\" == -* ]]; then\n"
    "    COMPREPLY=( $(compgen -W \"$opts\" -- \"$cur\") )\n"
    "    return 0\n"
    "  fi\n"
    "  COMPREPLY=()\n"
    "}\n"
    "complete -F _yume-setup_complete yume-setup\n";

}  // namespace yume::setup::setup_cli
